#!/usr/bin/env ruby
require 'rubygems'
require 'daemons'
require ::File.join(::File.dirname(__FILE__), '..', 'lib', 'linky')

# start DRb for worker process
#Daemons.run_proc('linky-worker.rb', :log_output => true) do
  worker = Linky::Databases::Worker.new
  DRb.start_service worker.uri, worker
  DRb.thread.join
#end

# vim:ft=ruby
