#!/usr/bin/env ruby
require 'rubygems'
require 'daemons'
require ::File.join(::File.dirname(__FILE__), '..', 'lib', 'linky')

# start DRb for worker process
drb = nil
unless ARGV[0] == "no-worker"
  drb = Daemons.call do
    worker = Linky::Databases::Worker.new
    DRb.start_service worker.uri, worker
    DRb.thread.join
  end
end

builder = Rack::Builder.new do
 use Rack::ShowExceptions
 use Linky::Application
 run Sinatra::Base
end
Rack::Handler::WEBrick.run(builder, :Port => 9292) do |server|
  DRb.start_service
  trap(:INT) do
    server.shutdown
    drb.stop  if drb
  end
end

# vim:ft=ruby
